version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-tictactoe
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  express-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: express-app
    depends_on:
      - mongodb
    ports:
      - "3005:3005"
    environment:
      MONGO_URI: mongodb://mongodb:27017/tic-tac-toe
    command: >
      sh -c " npm run start"
    volumes:
      - ./express-app:/app

  react-app:
    build:
      context: ./client  
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    depends_on:
      - express-app

volumes:
  mongo-data:
